services:
  apis:
    build:
      context: ./apis
    container_name: product_api
    ports:
      - "8000:8000"
    volumes:
      - ./apis:/app
    environment:
      - ENV=development
    working_dir: /app
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8000 --reload
