### Hello
POST http://localhost:8000/graphql
Content-Type: application/json

{
  "query": "query {hello}"
}

### Hello
POST http://localhost:8000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query {
  hello
}

### Créer un produit
POST http://localhost:8000/graphql
Content-Type: application/json

{
  "query": "mutation createProduct($product: ProductInput!) { createProduct(product: $product) }",
  "variables": {
    "product": {
      "code": "P001",
      "translations": [
        {
          "locale": "fr",
          "translation": {
            "title": "Produit FR",
            "description": "Description FR"
          }
        },
        {
          "locale": "en",
          "translation": {
            "title": "Product EN",
            "description": "EN desc"
          }
        }
      ]
    }
  }
}

### Créer un produit sans fr
POST http://localhost:8000/graphql
Content-Type: application/json

{
  "query": "mutation createProduct($product: ProductInput!) { createProduct(product: $product) }",
  "variables": {
    "product": {
      "code": "P999",
      "translations": [
        {
          "locale": "en",
          "translation": {
            "title": "Green Bike",
            "description": "A fast green bicycle"
          }
        }
      ]
    }
  }
}


### Lister les produits en français
POST http://localhost:8000/graphql
Content-Type: application/json

{
  "query": "query { products(locale: \"fr\") { code translation { title description } } }"
}
